# Generated by Django 5.0.3 on 2024-04-11 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_media_file_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='caption',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='Default description', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='details',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_admin_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='Default description', max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='Default description', upload_to='videos/%y'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(default='Default description', max_length=500)),
                ('details', models.TextField(default='Default description')),
                ('image', models.FileField(default='Default description', upload_to='image/%y')),
                ('is_admin_upload', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
