# Generated by Django 5.0.3 on 2024-04-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_images_date_media_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='images',
            name='details',
            field=models.TextField(default='Default detail'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='Default image', upload_to='image/%y'),
        ),
        migrations.AlterField(
            model_name='video',
            name='details',
            field=models.TextField(default='Default details'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='Default title', max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='Default video', upload_to='videos/%y'),
        ),
    ]
