# Generated by Django 5.0.3 on 2024-04-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_media_date_created_alter_images_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date',
        ),
    ]
