# Generated by Django 5.0.3 on 2024-04-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_images_date_remove_video_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='description',
        ),
        migrations.RemoveField(
            model_name='images',
            name='details',
        ),
    ]
