# Generated by Django 4.2.30 on 2026-05-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('manager', 'Manager'), ('admin', 'Admin')], default='member', max_length=10),
        ),
    ]
