# Generated by Django 5.0.3 on 2024-05-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='member_set',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member_id',
            new_name='id',
        ),
    ]
