# Generated by Django 5.0.3 on 2024-05-03 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_member_set_group_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='my_members',
            field=models.ManyToManyField(related_name='groups', to='myapp.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='myapp.group'),
        ),
    ]
