# Generated by Django 6.0.5 on 2026-05-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rolerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['-uploaded_at'], 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('service', 'Sunday Service'), ('revival', 'Revival / Crusade'), ('wedding', 'Wedding'), ('youth', 'Youth Event'), ('outreach', 'Community Outreach'), ('fundraiser', 'Fundraiser / Harambee'), ('seminar', 'Seminar / Conference'), ('anniversary', 'Church Anniversary'), ('baptism', 'Baptism / Communion'), ('prayer', 'Prayer Meeting / Vigil'), ('bible_study', 'Bible Study'), ('social', 'Social / Get-together'), ('other', 'Other')], default='service', max_length=20),
        ),
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.CharField(choices=[('service', 'Sunday Service'), ('sermon', 'Sermon'), ('wedding', 'Wedding'), ('youth', 'Youth Event'), ('outreach', 'Community Outreach'), ('fundraiser', 'Fundraiser / Harambee'), ('choir', 'Choir / Music'), ('anniversary', 'Church Anniversary'), ('baptism', 'Baptism / Communion'), ('prayer', 'Prayer Meeting'), ('bible_study', 'Bible Study'), ('celebration', 'Celebration / Party'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('service', 'Sunday Service'), ('sermon', 'Sermon'), ('wedding', 'Wedding'), ('youth', 'Youth Event'), ('outreach', 'Community Outreach'), ('fundraiser', 'Fundraiser / Harambee'), ('choir', 'Choir / Music'), ('anniversary', 'Church Anniversary'), ('baptism', 'Baptism / Communion'), ('prayer', 'Prayer Meeting'), ('bible_study', 'Bible Study'), ('celebration', 'Celebration / Party'), ('general', 'General')], default='sermon', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/%Y/'),
        ),
    ]
