# Generated by Django 6.0.5 on 2026-05-08 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_chatroom_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchChurch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('central_rift', 'Central Rift'), ('nyahururu', 'Nyahururu Town'), ('laikipia', 'Laikipia'), ('nyandarua', 'Nyandarua'), ('nakuru_north', 'Nakuru North'), ('other', 'Other')], default='central_rift', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('new', 'Newly Planted')], default='active', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['region', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('patron', 'Patron'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('chairperson', 'Chairperson'), ('leader', 'Leader'), ('pastor', 'Pastor'), ('reverend', 'Reverend / Bishop'), ('manager', 'Manager'), ('admin', 'Admin')], default='member', max_length=15),
        ),
        migrations.CreateModel(
            name='ChurchLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('reverend', 'Reverend / Bishop'), ('pastor', 'Pastor'), ('patron', 'Patron'), ('chairperson', 'Chairperson'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('elder', 'Elder'), ('deacon', 'Deacon'), ('deaconess', 'Deaconess'), ('worship', 'Worship Leader'), ('youth', 'Youth Leader'), ('other', 'Other')], max_length=20)),
                ('date_appointed', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='leaders/')),
                ('ordination_date', models.DateField(blank=True, null=True)),
                ('ordination_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(blank=True, help_text='Leave blank for HQ (RGC Nyahururu)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaders', to='myapp.branchchurch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ClergyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('salary', 'Monthly Salary'), ('allowance', 'Allowance'), ('tithe_share', 'Tithe Share'), ('transport', 'Transport Allowance'), ('housing', 'Housing Allowance'), ('medical', 'Medical Allowance'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(blank=True, help_text='e.g. May 2026', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_approved', to=settings.AUTH_USER_MODEL)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.branchchurch')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clergy_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegionalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('fellowship_group', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_members', to='myapp.branchchurch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['church', 'name'],
            },
        ),
    ]
