# Generated by Django 6.0.5 on 2026-05-08 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_branchchurch_alter_customuser_role_churchleader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_announcements', models.BooleanField(default=True)),
                ('email_events', models.BooleanField(default=True)),
                ('email_payments', models.BooleanField(default=True)),
                ('push_announcements', models.BooleanField(default=True)),
                ('push_events', models.BooleanField(default=True)),
                ('push_payments', models.BooleanField(default=True)),
                ('sms_payments', models.BooleanField(default=False)),
                ('whatsapp_otp', models.BooleanField(default=True)),
                ('whatsapp_payments', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notif_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SermonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scripture_ref', models.CharField(blank=True, help_text='e.g. John 3:16', max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('content', models.TextField(help_text='Sermon notes. Use --- to separate slides/sections.')),
                ('is_public', models.BooleanField(default=False, help_text='Allow all members to view this note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermon_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
