# Generated by Django 6.0.5 on 2026-05-08 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notificationpreference_sermonnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermonnote',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sermonnote',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who released this note to all members', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sermon_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sermonnote',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Released to all members by admin'),
        ),
    ]
