# Generated by Django 6.0.5 on 2026-05-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_sermonnote_approved_at_sermonnote_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_enabled', models.BooleanField(default=False, help_text='Show the Give / Contributions section to all logged-in members')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
